#- name: retrive the vault secrets
##  hosts: localhost
##  connection: local
##  become: yes
#  tasks:
#    - name: read the password
#      ansible.builtin.debug:
#        msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=test/data/demo token={{ pass_token }} url=http://vault.devopsmanju.shop:8200') }}"

#- name: Load Nodejs
#  ansible.builtin.include_role:
#    name: common
#    tasks_from: docker.yaml
#  vars:
#    app_port:80
#

- name: read the password
  ansible.builtin.set_fact:
    vault_secrets: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-dev-secrets/data/shipping token={{ pass_token }} url=http://vault.devopsmanju.shop:8200') }}"

- name: Build secrets dict from list
  ansible.builtin.set_fact:
    secrets: "{{ secrets | default({}) | combine({ item: vault_secrets[item] }) }}"
  loop: "{{ secret_keys }}"

- name: print the secrets
  ansible.builtin.debug:
    msg: "{{ secrets }}"

- name: print the secrets
  ansible.builtin.debug:
    msg: "{{ docker_secrets }}"